[package]
name = "axerr"
version = "0.1.0"
edition = "2021"

[dependencies]
axerr-derive = { path = "../axerr-derive" }

[dev-dependencies]
tokio = { version = "1.0", features = ["full"] }
axum = { version = "0.8" }
